#!/bin/bash
# shellcheck disable=SC1004,1090
set -o xtrace
set -o pipefail
set -o nounset
set -o errexit

source "cfg/${NAME}/bash_functions"

system_check () {
  UTILITES_LIST=("expect" "docker" "virsh" "virt-install")
  for UTILITY in "${UTILITES_LIST[@]}"; do
    if ! command -v "${UTILITY}" > /dev/null; then echo "${UTILITY} check error"; return 1; fi
  done

  if [ "${WRTLAB_PROXY_ENABLED}" = true ]; then
    curl -L http://downloads.openwrt.org/snapshots/targets/x86/64/version.buildinfo -s -o /dev/null -x "${WRTLAB_PROXY_URL_DOCKER}"
    curl -L http://downloads.openwrt.org/snapshots/targets/x86/64/version.buildinfo -s -o /dev/null -x "${WRTLAB_PROXY_URL_LIBVIRT}"
  fi
}

function build_image () {
  system_check

  #-------------------------------------------------
  if [ ! -d tmp ]; then mkdir -v tmp; fi
  if [ -d "tmp/${NAME}" ]; then rm -rv "tmp/${NAME}"; fi
  mkdir -v "tmp/${NAME}"
  cp -v Dockerfile "tmp/${NAME}/"
  cp -v dockerfile_bootstrap.sh "tmp/${NAME}/"
  cp -rvT cfg/default/ "tmp/${NAME}/"
  cp -rvT "cfg/${NAME}/" "tmp/${NAME}/"

  mkdir -p "tmp/${NAME}/files/etc/dropbear/"
  cp -v ~/.ssh/authorized_keys "tmp/${NAME}/files/etc/dropbear/"
  chmod og-rwx "tmp/${NAME}/files/etc/dropbear/"

  grep -R -l __NAME__ 				"tmp/${NAME}" | xargs sed -i "s%__NAME__%${NAME}%g"
  grep -R -l __WRTLAB_VERSION__			"tmp/${NAME}" | xargs sed -i "s%__WRTLAB_VERSION__%${WRTLAB_VERSION}%g"

  grep -R -l __WRTLAB_WAN_IF__ 			"tmp/${NAME}" | xargs sed -i "s%__WRTLAB_WAN_IF__%${WRTLAB_WAN_IF}%g"
  grep -R -l __WRTLAB_WAN_IP__                  "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_WAN_IP__%${WRTLAB_WAN_IP}%g"
  grep -R -l __WRTLAB_WAN_MASK__                "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_WAN_MASK__%${WRTLAB_WAN_MASK}%g"
  grep -R -l __WRTLAB_WAN_GW__                  "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_WAN_GW__%${WRTLAB_WAN_GW}%g"
  grep -R -l __WRTLAB_WAN_DNS__                 "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_WAN_DNS__%${WRTLAB_WAN_DNS}%g"

  grep -R -l __WRTLAB_VPN_NET__                 "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_VPN_NET__%${WRTLAB_VPN_NET}%g"
  grep -R -l __WRTLAB_VPN_IP__                  "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_VPN_IP__%${WRTLAB_VPN_IP}%g"
  grep -R -l __WRTLAB_VPN_MASK_SHORT__          "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_VPN_MASK_SHORT__%${WRTLAB_VPN_MASK_SHORT}%g"
  grep -R -l __WRTLAB_VPN_PORT__                "tmp/${NAME}" | xargs sed -i "s/__WRTLAB_VPN_PORT__/${WRTLAB_VPN_PORT}/g"
  grep -R -l __WRTLAB_VPN_PORT_HIDDEN__         "tmp/${NAME}" | xargs sed -i "s/__WRTLAB_VPN_PORT_HIDDEN__/${WRTLAB_VPN_PORT_HIDDEN}/g"

  grep -R -l __WRTLAB_TEST_VPN_IP__             "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_TEST_VPN_IP__%${WRTLAB_TEST_VPN_IP}%g"
  grep -R -l __WRTLAB_TEST_VPN_GW__             "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_TEST_VPN_GW__%${WRTLAB_TEST_VPN_GW}%g"
  grep -R -l __WRTLAB_TEST_VPN_NET__            "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_TEST_VPN_NET__%${WRTLAB_TEST_VPN_NET}%g"
  grep -R -l __WRTLAB_TEST_VPN_MASK_SHORT__     "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_TEST_VPN_MASK_SHORT__%${WRTLAB_TEST_VPN_MASK_SHORT}%g"

  grep -R -l __WRTLAB_PROXY_ENABLED__           "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_PROXY_ENABLED__%${WRTLAB_PROXY_ENABLED}%g"
  grep -R -l __WRTLAB_PROXY_URL_DOCKER__        "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_PROXY_URL_DOCKER__%${WRTLAB_PROXY_URL_DOCKER}%g"
  grep -R -l __WRTLAB_PROXY_URL_LIBVIRT__       "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_PROXY_URL_LIBVIRT__%${WRTLAB_PROXY_URL_LIBVIRT}%g"
  grep -R -l __WRTLAB_PROXY_FEDORA_MAIN__       "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_PROXY_FEDORA_MAIN__%${WRTLAB_PROXY_FEDORA_MAIN}%g"
  grep -R -l __WRTLAB_PROXY_FEDORA_CODECS__     "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_PROXY_FEDORA_CODECS__%${WRTLAB_PROXY_FEDORA_CODECS}%g"

  specific_build_image

  #-------------------------------------------------
  if ! docker inspect --type=image "wrtlab:${WRTLAB_VERSION}" > /dev/null; then
    cd "tmp/${NAME}/"
    docker build -t "wrtlab:${WRTLAB_VERSION}" .
    cd ../..
  fi

  rm -rfv img/*

  PACKAGES="cgi-io libiwinfo libiwinfo-data libiwinfo-lua liblua liblucihttp liblucihttp-lua libubus-lua lua luci luci-app-firewall luci-app-opkg luci-base luci-lib-base luci-lib-ip luci-lib-jsonc luci-lib-nixio luci-mod-admin-full luci-mod-network luci-mod-status luci-mod-system luci-proto-ppp luci-ssl px5g-wolfssl rpcd rpcd-mod-file rpcd-mod-iwinfo rpcd-mod-luci rpcd-mod-rrdns uhttpd uhttpd-mod-ubus luci-app-wireguard arp-scan arp-scan-database grub2 grub2-efi kmod-fs-vfat kmod-nls-base kmod-nls-cp437 kmod-nls-iso8859-1 kmod-nls-utf8 iperf3 openssh-client-utils"
  FILES="tmp/${NAME}"

  docker run -it --rm -v "${PWD}:/opt:Z" \
  --env "IMG_NAME=${NAME}" --env "IMG_VERSION=${WRTLAB_VERSION}" \
  --env "IMG_FILES=${FILES}" --env "PACKAGES=${PACKAGES}" \
  --env "IMG_PROXY_ENABLED=${WRTLAB_PROXY_ENABLED}" --env "IMG_PROXY_URL=${WRTLAB_PROXY_URL_DOCKER}" \
  "wrtlab:${WRTLAB_VERSION}" bash -c '\
    set -o nounset; set -o errexit; set -o xtrace;
    if [ "${IMG_PROXY_ENABLED}" = true ]; then sed -i -e "s/https/http/" repositories.conf && echo "option http_proxy ${IMG_PROXY_URL}" >> repositories.conf && cat repositories.conf; fi && \
    make -j4 image FILES="/opt/${IMG_FILES}/files" BIN_DIR="/opt/${IMG_FILES}/img" PACKAGES="$PACKAGES"; \
    cd "/opt/${IMG_FILES}/img"; gzip -d "openwrt-${IMG_VERSION}-x86-64-generic-ext4-combined.img.gz" || true; \
    qemu-img convert -f raw -O qcow2 "openwrt-${IMG_VERSION}-x86-64-generic-ext4-combined.img" "${IMG_NAME}.qcow2"'
    #guestmount -a tmp/rr1router.qcow2 -i --rw mnt/
}

function virtnet_setup () {
  #-------------------------------------------------
  if [ "${WRTLAB_VIRT_NETWORKS_ENABLED}" = true ]; then
    if ! virsh net-info default | grep -q "Active:         yes"; then
      virsh net-start default
    fi

    if ! virsh net-dumpxml default | grep -q "<host mac='$WRTLAB_WAN_MAC' ip='$WRTLAB_WAN_IP'/>"; then
      if virsh net-dumpxml default | grep -q "host mac='$WRTLAB_WAN_MAC'"; then
        virsh net-update default modify ip-dhcp-host "<host mac='$WRTLAB_WAN_MAC' ip='$WRTLAB_WAN_IP'/>" --live --config --parent-index 0
      else
        virsh net-update default add-last ip-dhcp-host "<host mac='$WRTLAB_WAN_MAC' ip='$WRTLAB_WAN_IP'/>" --live --config --parent-index 0
      fi
    fi
    specific_virtnet_setup  
  fi
}

function deploy () {

  remove_vm "${NAME}"
  specific_deploy
  virtnet_setup

  if [ ! -d "$LIBVIRT_DIR_POOL_PATH" ]; then
    mkdir "$LIBVIRT_DIR_POOL_PATH" || true
    chown "${USER}:qemu" "$LIBVIRT_DIR_POOL_PATH"
    chmod g+rws "$LIBVIRT_DIR_POOL_PATH"
  fi
  cp -v "tmp/${NAME}/img/${NAME}.qcow2" "$LIBVIRT_DIR_POOL_PATH"
  
  #osinfo-query os
  virt-install -n "${NAME}" --install no_install=yes \
   --vcpus 1 --ram 128 --video none --graphics none  \
   --osinfo linux2020 --disk path="${LIBVIRT_DIR_POOL_PATH}/${NAME}.qcow2" \
   "${WRTLAB_WAN_NETWORKS[@]}" \
   "${WRTLAB_LOCAL_NETWORKS[@]}" \
   --noautoconsole

  virsh autostart "${NAME}"
}

function test () {
  # default test
  cfg/default/tests/router_internal_test.exp "${NAME}"

  # specific test
  specific_test  
}

function remove_vm () {
  local NAME=$1
  if virsh dominfo "${NAME}" &> /dev/null; then
    if virsh dominfo "${NAME}" | grep -q "State:          running"; then
      virsh destroy "${NAME}"
    fi
    virsh undefine "${NAME}"
  fi

}

function net_deploy () {
  local NET_NAME=$1
  local HOST_IP=$2
  local NET_MASK=$3

  if virsh net-info "${NET_NAME}"; then
    if virsh net-info "${NET_NAME}" | grep -q "Active:         yes"; then
      virsh net-destroy "${NET_NAME}"
    fi
    virsh net-undefine "${NET_NAME}"
  fi

  virsh net-define <(cat << EOF
<network>
  <name>${NET_NAME}</name>
  <bridge stp='off'/>
  <ip address='${HOST_IP}' netmask='${NET_MASK}'>
  </ip>
</network>
EOF
)
  virsh net-start "${NET_NAME}"
}

function run_alpine315_test () {
  local VM=$1
  local TEST=$2
  local NET=$3
  local MAC=$4

  if [ ! -f "${LIBVIRT_DIR_POOL_PATH}/alpine-virt-3.15.0-x86_64.iso" ]; then
    WRTLAB_PATH="$PWD"
    mkdir "$LIBVIRT_DIR_POOL_PATH" || true && cd "$LIBVIRT_DIR_POOL_PATH"
    curl -LO https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/x86_64/alpine-virt-3.15.0-x86_64.iso
    curl -LO https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/x86_64/alpine-virt-3.15.0-x86_64.iso.sha256
    sha256sum --ignore-missing -c alpine-virt-3.15.0-x86_64.iso.sha256
    rm -v alpine-virt-3.15.0-x86_64.iso.sha256
    cd "$WRTLAB_PATH"
  fi

  remove_vm "${VM}"
  virt-install -n "${VM}" --install no_install=yes \
   --vcpus 1 --ram 256 --video none --graphics none \
   --osinfo alpinelinux3.14 --disk device=cdrom,path="${LIBVIRT_DIR_POOL_PATH}/alpine-virt-3.15.0-x86_64.iso" \
   --network "network=${NET},mac=${MAC}" \
   --noautoconsole
  "tmp/${NAME}/tests/router_external_${TEST}.exp" "${VM}"
}

