#!/usr/bin/expect -f
#AUTHOR="Semyon Vasilkov <github@zimmnik.ru>"
#FYI https://pantz.org/software/expect/expect_examples_and_tips.html

set name [lindex $argv 0]
if {[llength $argv] == 0} {
  send_user "Usage: scriptname virsh_domain_name\n"
  exit 1
}

log_user 1

send_user "\nmngt setup started \n\n"

spawn virsh console $name

set timeout 10
expect {
  "localhost login: $" {}
  default { send_user "FAIL: console error\n"; exit 1 }
}

send -- "root\r"
set prompt "localhost:~#"
set timeout 3
expect {
  -re $prompt { send -- "\r" }
  default { send_user "\nFAIL: prompt error\n"; exit 1 }
}

send -- "\
ip a add __WRTLAB_MNGT_IP_HOST__/24 dev eth0 && \
ip link set dev eth0 up && \
ip route add default via __WRTLAB_MNGT_IP__ && \
echo \"nameserver __WRTLAB_MNGT_IP__\" >> /etc/resolv.conf && \
ip r && \
ping -c 1 __WRTLAB_MNGT_IP__\r"
set timeout 10
expect {
  " 0% packet loss" {}
  default { send_user "FAIL: gateway ping error\n"; exit 1 }
}

send -- "ping -c 1 ya.ru\r"
set timeout 10
expect {
  " 0% packet loss" {}
  default { send_user "FAIL: internet ping error\n"; exit 1 }
}

send_user "\nmngt setup completed successfully\n\n"
close
