#!/usr/bin/expect -f
#VERSION=220206
#AUTHOR="Semyon Vasilkov <github@zimmnik.ru>"
#FYI https://pantz.org/software/expect/expect_examples_and_tips.html

set name [lindex $argv 0]
if {[llength $argv] == 0} {
  send_user "Usage: scriptname virsh_domain_name\n"
  exit 1
}

log_user 1

send_user "\nExternal test started ... \n"

spawn virsh console $name

set timeout 60
expect {
  "localhost-live login\: \$" {}
  default { send_user "FAIL: console error\n"; exit 1 }
}

send -- "root\r"
set timeout 3
expect {
  "root@localhost-live" {}
  default { send_user "FAIL: prompt error\n"; exit 1 }
}

send -- "ping -c 1 8.8.8.8\r"
set timeout 5
expect {
  " 0% packet loss" {}
  default { send_user "FAIL: ping error\n"; exit 1 }
}

#send -- "yum -y install xterm\r"
#set timeout 100
#expect {
#  "Complete!" {}
#  default { send_user "FAIL: resize error\n"; exit 1 }
#}
#
#send -- "eval /usr/bin/resize\r\r"
#set timeout 5
#expect {
#  "localhost-live" {}
#  default { send_user "FAIL: resize error\n"; exit 1 }
#}

send -- "echo yandex | passwd root --stdin && echo \"PermitRootLogin yes\" >> /etc/ssh/sshd_config && systemctl restart sshd && sleep 2 && ssh-keyscan -4 -t rsa localhost\r"
set timeout 10
expect {
  "localhost ssh-rsa AAAA" {}
  default { send_user "FAIL: sshd error\n"; exit 1 }
}

send_user "\nTest passed successfully\n\n"
close
