#!/usr/bin/expect -f
#VERSION=220206
#AUTHOR="Semyon Vasilkov <github@zimmnik.ru>"
#FYI https://pantz.org/software/expect/expect_examples_and_tips.html

set name [lindex $argv 0]
if {[llength $argv] == 0} {
  send_user "Usage: scriptname virsh_domain_name\n"
  exit 1
}

log_user 1

#set send_slow {1 .1}
#proc send {ignore arg} {
#        sleep .2
#        exp_send -s -- $arg
#}

send_user "\nExternal test started ... \n"

spawn virsh reset $name
spawn virsh console $name

set timeout 10
expect {
  "localhost login: $" {}
  default { send_user "FAIL: console error\n"; exit 1 }
}

send -- "root\r"
set prompt "localhost:~#"
set timeout 3
expect {
  -re $prompt { send -- "\r" }
  default { send_user "\nFAIL: prompt error\n"; exit 1 }
}

#send -- "KEYMAPOPTS=\"us us\" setup-alpine -q && ping -c 1 172.28.1.1\r"
send -- "KEYMAPOPTS=\"us us\" setup-alpine -q && ping -c 1 8.8.8.8\r"
set timeout 10
expect {
  " 0% packet loss" {}
  default { send_user "FAIL: ping error\n"; exit 1 }
}

send -- "apk add openssh && rc-service sshd start && sleep 2 && ssh-keyscan -4 -t rsa localhost\r"
set timeout 11
expect {
  "localhost ssh-rsa AAAA" {}
  default { send_user "\nFAIL: ssh setup error\n"; exit 1 }
}

send_user "\nTest passed successfully\n\n"
close
