#!/bin/bash
# shellcheck disable=SC1004,2034
#set -o xtrace
set -o pipefail
set -o nounset
set -o errexit

WRTLAB_WAN_IF="eth0"
WRTLAB_WAN_IP="10.64.0.253"
WRTLAB_WAN_MASK="255.255.255.0"
WRTLAB_WAN_GW="10.64.0.254"
WRTLAB_WAN_DNS="10.64.0.254"
WRTLAB_WAN_MAC="52:54:00:55:02:00"

WRTLAB_MNGT_IF="eth1"
WRTLAB_MNGT_IP="192.168.1.254"
WRTLAB_MNGT_MASK_LONG="255.255.255.0"
WRTLAB_MNGT_NAME="${NAME}_mngt"
WRTLAB_MNGT_IP_HOST="192.168.1.253"

WRTLAB_HOME_IF="eth2"
WRTLAB_HOME_IP="192.168.4.254"
WRTLAB_HOME_MASK_LONG="255.255.255.0"
WRTLAB_HOME_NAME="${NAME}_home"
WRTLAB_HOME_IP_HOST="192.168.4.253"

WRTLAB_DMZ_IF="eth3"
WRTLAB_DMZ_IP="192.168.3.254"
WRTLAB_DMZ_MASK_LONG="255.255.255.0"
WRTLAB_DMZ_NAME="${NAME}_dmz"
WRTLAB_DMZ_IP_HOST="192.168.3.253"

WRTLAB_VPN_IP="192.168.5.254"
WRTLAB_VPN_MASK_SHORT="24"
WRTLAB_VPN_NET="192.168.5.0/24"
WRTLAB_VPN_PORT="5151"
WRTLAB_VPN_PORT_HIDDEN="53"

WRTLAB_TEST_VPN_IP="192.168.5.200"
WRTLAB_TEST_VPN_MASK_SHORT="32"
WRTLAB_TEST_VPN_GW="192.168.5.254"
WRTLAB_TEST_VPN_NET="192.168.5.0/24"
WRTLAB_TEST_VPN_EXT_MAC="52:54:00:55:02:01"

WRTLAB_TEST_MNGT_IP="192.168.1.252"
WRTLAB_TEST_MNGT_MAC="52:54:00:55:02:02"

WRTLAB_TEST_HOME_IP="192.168.4.252"
WRTLAB_TEST_HOME_MAC="52:54:00:55:02:03"

WRTLAB_TEST_DMZ_IP="192.168.3.252"
WRTLAB_TEST_DMZ_MAC="52:54:00:55:02:04"

WRTLAB_WAN_NETWORKS=(--network "network=default,mac=${WRTLAB_WAN_MAC}")
WRTLAB_LOCAL_NETWORKS=(--network "network=${WRTLAB_MNGT_NAME}" --network "network=${WRTLAB_HOME_NAME}" --network "network=${WRTLAB_DMZ_NAME}")
WRTLAB_TEST_VPN_EXT_NETWORKS=(--network "network=default,mac=${WRTLAB_TEST_VPN_EXT_MAC}")
#export WRTLAB_LOCAL_NETWORKS=(--network "network=default,mac=${WRTLAB_WAN_MAC}")
#export NET_INET="type=direct,source=eno1,source_mode=bridge"

function bake_vars_specific () {
  #FYI https://unix.stackexchange.com/questions/330660/prevent-grep-from-exiting-in-case-of-nomatch
  grep -R -l __WRTLAB_MNGT_IF__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_MNGT_IF__%${WRTLAB_MNGT_IF}%g"               || [[ $? == 1 ]]
  grep -R -l __WRTLAB_MNGT_IP__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_MNGT_IP__%${WRTLAB_MNGT_IP}%g"               || [[ $? == 1 ]]
  grep -R -l __WRTLAB_MNGT_IP_HOST__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_MNGT_IP_HOST__%${WRTLAB_MNGT_IP_HOST}%g"     || [[ $? == 1 ]] 
  grep -R -l __WRTLAB_MNGT_MASK_LONG__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_MNGT_MASK_LONG__%${WRTLAB_MNGT_MASK_LONG}%g" || [[ $? == 1 ]]

  grep -R -l __WRTLAB_HOME_IF__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_HOME_IF__%${WRTLAB_HOME_IF}%g"               || [[ $? == 1 ]]
  grep -R -l __WRTLAB_HOME_IP__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_HOME_IP__%${WRTLAB_HOME_IP}%g"               || [[ $? == 1 ]]
  grep -R -l __WRTLAB_HOME_MASK_LONG__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_HOME_MASK_LONG__%${WRTLAB_HOME_MASK_LONG}%g" || [[ $? == 1 ]]

  grep -R -l __WRTLAB_DMZ_IF__ 			"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_DMZ_IF__%${WRTLAB_DMZ_IF}%g"                 || [[ $? == 1 ]]
  grep -R -l __WRTLAB_DMZ_IP__ 			"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_DMZ_IP__%${WRTLAB_DMZ_IP}%g"                 || [[ $? == 1 ]]
  grep -R -l __WRTLAB_DMZ_MASK_LONG__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_DMZ_MASK_LONG__%${WRTLAB_DMZ_MASK_LONG}%g"   || [[ $? == 1 ]]

  grep -R -l __WRTLAB_TEST_MNGT_IP__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_TEST_MNGT_IP__%${WRTLAB_TEST_MNGT_IP}%g"     || [[ $? == 1 ]]
  grep -R -l __WRTLAB_TEST_MNGT_MAC__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_TEST_MNGT_MAC__%${WRTLAB_TEST_MNGT_MAC}%g"   || [[ $? == 1 ]]

  grep -R -l __WRTLAB_TEST_HOME_IP__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_TEST_HOME_IP__%${WRTLAB_TEST_HOME_IP}%g"     || [[ $? == 1 ]]
  grep -R -l __WRTLAB_TEST_HOME_MAC__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_TEST_HOME_MAC__%${WRTLAB_TEST_HOME_MAC}%g"   || [[ $? == 1 ]]

  grep -R -l __WRTLAB_TEST_DMZ_IP__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_TEST_DMZ_IP__%${WRTLAB_TEST_DMZ_IP}%g"       || [[ $? == 1 ]]
  grep -R -l __WRTLAB_TEST_DMZ_MAC__ 		"tmp/${NAME}" | xargs --no-run-if-empty sed -i "s%__WRTLAB_TEST_DMZ_MAC__%${WRTLAB_TEST_DMZ_MAC}%g"     || [[ $? == 1 ]]
}

function create_virtnet_specific () {
  net_deploy "${WRTLAB_MNGT_NAME}" "${WRTLAB_MNGT_IP_HOST}" "${WRTLAB_MNGT_MASK_LONG}"
  net_deploy "${WRTLAB_HOME_NAME}" "${WRTLAB_HOME_IP_HOST}" "${WRTLAB_HOME_MASK_LONG}"
  net_deploy "${WRTLAB_DMZ_NAME}"  "${WRTLAB_DMZ_IP_HOST}"  "${WRTLAB_DMZ_MASK_LONG}"
}

function specific_test () {
  remove_vm "${NAME}_testvpn"
  remove_vm "${NAME}_testmngt"
  remove_vm "${NAME}_testhome"
  remove_vm "${NAME}_testdmz"

  if [ ! -f "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-36-1.5.iso" ]; then
    WRTLAB_PATH="$PWD"
    mkdir "$LIBVIRT_DIR_POOL_PATH" || true && cd "$LIBVIRT_DIR_POOL_PATH"
    curl -LO https://download.fedoraproject.org/pub/fedora/linux/releases/36/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-36-1.5.iso
    curl -LO https://download.fedoraproject.org/pub/fedora/linux/releases/36/Workstation/x86_64/iso/Fedora-Workstation-36-1.5-x86_64-CHECKSUM
    sha256sum --ignore-missing -c Fedora-Workstation-36-1.5-x86_64-CHECKSUM
    rm -v Fedora-Workstation-36-1.5-x86_64-CHECKSUM
    cd "$WRTLAB_PATH"
  fi

  remove_vm "${NAME}_testvpn"
  virt-install -n "${NAME}_testvpn" --install no_install=no \
   --vcpus 1 --ram 2048 --video none --graphics none \
   --osinfo linux2020 --disk none --location "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-36-1.5.iso" \
   --extra-args "console=ttyS0 root=live:CDLABEL=Fedora-WS-Live-36-1-5 rd.live.image systemd.unit=multi-user.target" \
   "${WRTLAB_TEST_VPN_EXT_NETWORKS[@]}" \
   --noautoconsole
  "tmp/${NAME}/tests/router_external_test_vpn.exp" "${NAME}_testvpn"

  run_alpine315_test "${NAME}_testmngt" testmngt "${WRTLAB_MNGT_NAME}" "${WRTLAB_TEST_MNGT_MAC}"
  run_alpine315_test "${NAME}_testdmz"  testdmz  "${WRTLAB_DMZ_NAME}"  "${WRTLAB_TEST_DMZ_MAC}"
  run_alpine315_test "${NAME}_testhome" testhome "${WRTLAB_HOME_NAME}" "${WRTLAB_TEST_HOME_MAC}"
}
