#!/usr/bin/expect -f
#FYI https://pantz.org/software/expect/expect_examples_and_tips.html

set name [lindex $argv 0]
if {[llength $argv] == 0} {
  send_user "Usage: scriptname virsh_domain_name\n"
  exit 1
}

log_user 1

set send_slow {1 .1}
proc send {ignore arg} {
        sleep .2
        exp_send -s -- $arg
}

send_user "\nrouter testing started\n\n"

#spawn virsh reset $name
spawn virsh console $name

#flush stdout
#send -- "time ping -c 1 172.28.1.1\r"
send -- "ping -c 1 8.8.8.8\r"
set timeout 10
expect {
  " 0% packet loss" {}
  default { send_user "FAIL: ping error\n"; exit 1 }
}

send_user "\nrouter testing completed successfully\n\n"
close
