#!/usr/bin/expect -f
#AUTHOR="Semyon Vasilkov <github@zimmnik.ru>"
#FYI https://pantz.org/software/expect/expect_examples_and_tips.html

set name [lindex $argv 0]
if {[llength $argv] == 0} {
  send_user "Usage: scriptname virsh_domain_name\n"
  exit 1
}

log_user 1

send_user "\nvpn setup started \n\n"

spawn virsh console $name

set timeout 60
expect {
  "localhost-live login\: \$" {}
  default { send_user "FAIL: console error\n"; exit 1 }
}

send -- "root\r"
set timeout 3
expect {
  "root@localhost-live" {}
  default { send_user "FAIL: prompt error\n"; exit 1 }
}

set proxy_enabled __WRTLAB_PROXY_ENABLED__
set proxy_url __WRTLAB_PROXY_URL_LIBVIRT__
set proxy_fedora_main __WRTLAB_PROXY_FEDORA_MAIN__
set proxy_fedora_codecs __WRTLAB_PROXY_FEDORA_CODECS__

if {$proxy_enabled == true} {
send -- "\
sed -i '/fedora-cisco-openh264-\$releasever/i \#baseurl=$proxy_fedora_codecs/\$releasever/\$basearch/os/' /etc/yum.repos.d/fedora-cisco-openh264.repo && \
sed -i 's%http://download.example/pub/fedora%$proxy_fedora_main%g' \$(grep -ril 'baseurl' /etc/yum.repos.d/) && \
sed -i 's/#baseurl/baseurl/g' \$(grep -ril 'baseurl' /etc/yum.repos.d/) && \
sed -i 's/metalink/#metalink/g' \$(grep -ril 'metalink' /etc/yum.repos.d/) && \
echo -e 'deltarpm=false\nzchunk=false\nproxy=$proxy_url' | tee -a /etc/dnf/dnf.conf
\r"
} 

send -- "yum -y install xterm-resize wireguard-tools\r"
set timeout 180
expect {
  "Complete!" {}
  default { send_user "FAIL: yum install error\n"; exit 1 }
}

set timeout 10
send -- "nmcli connection add type wireguard con-name VPN ifname wg0 \
ipv6.method disabled ipv4.method manual ipv4.addresses __WRTLAB_TEST_VPN_IP__/__WRTLAB_TEST_VPN_MASK_SHORT__ \
ipv4.dns __WRTLAB_TEST_VPN_GW__ ipv4.dns-priority -100 \
wireguard.private-key \"zUHaNRpdy/cJU8juzmHlIbcL7pZOuLn33MVmDJy1UBg=\" && \
cat << 'EOF' >> /etc/NetworkManager/system-connections/VPN.nmconnection

\[wireguard-peer.hkz1yY3FvAclZtP45C1wyQUS2gUqWVZIIduebVcrCH4=\]
endpoint=__WRTLAB_WAN_IP__:__WRTLAB_VPN_PORT_HIDDEN__
persistent-keepalive=25
#allowed-ips=__WRTLAB_TEST_VPN_NET__;
allowed-ips=0.0.0.0/0;
EOF
nmcli connection load /etc/NetworkManager/system-connections/VPN.nmconnection && \
nmcli connection up VPN\r"
set timeout 10
expect {
  "successfully added" {}
  default { send_user "FAIL: nmcli error\n"; exit 1 }
}
sleep 2

send -- "ping -c 1 __WRTLAB_VPN_IP__\r"
set timeout 10
expect {
  " 0% packet loss" {}
  default { send_user "FAIL: gateway ping error\n"; exit 1 }
}

send -- "ping -c 1 ya.ru\r"
set timeout 10
expect {
  " 0% packet loss" {}
  default { send_user "FAIL: internet ping error\n"; exit 1 }
}

send -- "traceroute ya.ru; resolvectl query ya.ru"
sleep 10

send_user "\nvpn setup completed successfully\n\n"
close
