#!/bin/bash
# VERSION=220223
# shellcheck disable=SC1004
set -o xtrace
set -o pipefail
set -o nounset
set -o errexit

function specific_build_image () {
  sed -i "s/__WRTLAB_WAN_MASK__/${WRTLAB_WAN_MASK}/" "tmp/${NAME}/files/etc/uci-defaults/99_custom"
  sed -i "s/__WRTLAB_WAN_GW__/${WRTLAB_WAN_GW}/" "tmp/${NAME}/files/etc/uci-defaults/99_custom"
  sed -i "s/__WRTLAB_WAN_DNS__/${WRTLAB_WAN_DNS}/" "tmp/${NAME}/files/etc/uci-defaults/99_custom"
  sed -i "s%__WRTLAB_VPN_IP__%${WRTLAB_VPN_IP}%" "tmp/${NAME}/files/etc/uci-defaults/99_custom"
  sed -i "s%__WRTLAB_VPN_NET__%${WRTLAB_VPN_NET}%" "tmp/${NAME}/files/etc/uci-defaults/99_custom"

  sed -i "s%__WRTLAB_TEST_VPN_IP__%${WRTLAB_TEST_VPN_IP}%" "tmp/${NAME}/tests/router_external_test.exp"
  sed -i "s%__WRTLAB_TEST_VPN_GW__%${WRTLAB_TEST_VPN_GW}%" "tmp/${NAME}/tests/router_external_test.exp"

  grep -R -l __WRTLAB_WAN_IP__ "tmp/${NAME}" | xargs sed -i "s%__WRTLAB_WAN_IP__%${WRTLAB_WAN_IP}%g"
  grep -R -l __WRTLAB_VPN_PORT__ "tmp/${NAME}" | xargs sed -i "s/__WRTLAB_VPN_PORT__/${WRTLAB_VPN_PORT}/g"
  grep -R -l __WRTLAB_VPN_PORT_HIDDEN__ "tmp/${NAME}" | xargs sed -i "s/__WRTLAB_VPN_PORT_HIDDEN__/${WRTLAB_VPN_PORT_HIDDEN}/g"
}

function specific_test () {
  if virsh dominfo "${NAME}_testclient" &> /dev/null; then
    if virsh dominfo "${NAME}_testclient" | grep -q "State:          running"; then
      virsh destroy "${NAME}_testclient"
    fi
    virsh undefine "${NAME}_testclient"
  fi

  if [ ! -f "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-34-1.2.iso" ]; then
    WRTLAB_PATH="$PWD"
    mkdir "$LIBVIRT_DIR_POOL_PATH" || true && cd "$LIBVIRT_DIR_POOL_PATH"
    curl -LO https://mirror.yandex.ru/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso
    curl -LO https://mirror.yandex.ru/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    sha256sum --ignore-missing -c Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    rm -v Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    cd "$WRTLAB_PATH"
  fi

  virt-install -n "${NAME}_testclient" --install no_install=no \
   --vcpus 1 --ram 2048 --video none --graphics none \
   --osinfo linux2020 --disk none --location "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-34-1.2.iso" \
   --extra-args "console=ttyS0 root=live:CDLABEL=Fedora-WS-Live-34-1-2 rd.live.image systemd.unit=multi-user.target" \
   --network "${NET_INET}" \
   --noautoconsole
  
  "tmp/${NAME}/tests/router_external_test.exp" "${NAME}_testclient"
}
