#!/bin/bash
# shellcheck disable=SC1004
set -o xtrace
set -o pipefail
set -o nounset
set -o errexit


function specific_build_image () {
  :
}

function specific_virtnet_setup () {
  :
}

function specific_deploy () {
  :
}


function specific_test () {
  if [ ! -f "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-36-1.5.iso" ]; then
    WRTLAB_PATH="$PWD"
    mkdir "$LIBVIRT_DIR_POOL_PATH" || true && cd "$LIBVIRT_DIR_POOL_PATH"
    curl -LO https://mirror.yandex.ru/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-36-1.5.iso
    curl -LO https://mirror.yandex.ru/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    sha256sum --ignore-missing -c Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    rm -v Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    cd "$WRTLAB_PATH"
  fi

  remove_vm "${NAME}_testvpn"
  virt-install -n "${NAME}_testvpn" --install no_install=no \
   --vcpus 1 --ram 2048 --video none --graphics none \
   --osinfo linux2020 --disk none --location "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-36-1.5.iso" \
   --extra-args "console=ttyS0 root=live:CDLABEL=Fedora-WS-Live-36-1-5 rd.live.image systemd.unit=multi-user.target" \
   "${WRTLAB_TEST_NETWORKS[@]}" \
   --noautoconsole
  
  "tmp/${NAME}/tests/router_external_test_vpn.exp" "${NAME}_testvpn"
}
