#!/bin/bash
# shellcheck disable=SC1004,2034
set -o xtrace
set -o pipefail
set -o nounset
set -o errexit

WRTLAB_WAN_IF="eth0"
WRTLAB_WAN_IP="192.168.122.102"
WRTLAB_WAN_MASK="255.255.255.0"
WRTLAB_WAN_GW="192.168.122.1"
WRTLAB_WAN_DNS="192.168.122.1"
WRTLAB_WAN_MAC="52:54:00:55:01:00"
WRTLAB_WAN_NETWORKS=(--network "network=default,mac=${WRTLAB_WAN_MAC}")

WRTLAB_VPN_IP="192.168.99.254"
WRTLAB_VPN_MASK_SHORT="24"
WRTLAB_VPN_NET="192.168.99.0/24"
WRTLAB_VPN_PORT="5151"
WRTLAB_VPN_PORT_HIDDEN="53"

WRTLAB_TEST_VPN_IP="192.168.99.200"
WRTLAB_TEST_VPN_MASK_SHORT="32"
WRTLAB_TEST_VPN_GW="192.168.99.254"
WRTLAB_TEST_VPN_NET="0.0.0.0/0"
WRTLAB_TEST_VPN_EXT_MAC="52:54:00:55:01:01"
WRTLAB_TEST_VPN_EXT_NETWORKS=(--network "network=default,mac=${WRTLAB_TEST_VPN_EXT_MAC}")

WRTLAB_LOCAL_NETWORKS=(--network none)
#export NET_INET="type=direct,source=eno1,source_mode=bridge"

WRTLAB_PROXY_ENABLED="true"
WRTLAB_PROXY_URL_LIBVIRT="http://${WRTLAB_WAN_GW}:3128"
WRTLAB_PROXY_URL_DOCKER="http://${HOSTNAME}:3128"
WRTLAB_PROXY_FEDORA_MAIN="http://ftp.halifax.rwth-aachen.de/fedora"
WRTLAB_PROXY_FEDORA_CODECS="http://codecs.fedoraproject.org/openh264"


function specific_build_image () {
  :
}

function specific_virtnet_setup () {
  :
}

function specific_deploy () {
  :
}


function specific_test () {
  if [ ! -f "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-36-1.5.iso" ]; then
    WRTLAB_PATH="$PWD"
    mkdir "$LIBVIRT_DIR_POOL_PATH" || true && cd "$LIBVIRT_DIR_POOL_PATH"
    curl -LO https://mirror.yandex.ru/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-36-1.5.iso
    curl -LO https://mirror.yandex.ru/fedora/linux/releases/34/Workstation/x86_64/iso/Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    sha256sum --ignore-missing -c Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    rm -v Fedora-Workstation-34-1.2-x86_64-CHECKSUM
    cd "$WRTLAB_PATH"
  fi

  remove_vm "${NAME}_testvpn"
  virt-install -n "${NAME}_testvpn" --install no_install=no \
   --vcpus 1 --ram 2048 --video none --graphics none \
   --osinfo linux2020 --disk none --location "${LIBVIRT_DIR_POOL_PATH}/Fedora-Workstation-Live-x86_64-36-1.5.iso" \
   --extra-args "console=ttyS0 root=live:CDLABEL=Fedora-WS-Live-36-1-5 rd.live.image systemd.unit=multi-user.target" \
   "${WRTLAB_TEST_VPN_EXT_NETWORKS[@]}" \
   --noautoconsole
  
  "tmp/${NAME}/tests/router_external_test_vpn.exp" "${NAME}_testvpn"
}
